# Generated by Django 5.0.6 on 2024-06-02 01:11

import SM.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0002_profile_birth_date_profile_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to=SM.models.user_directory_path),
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
